name: run-tests

on:
    push:
        paths:
            - '**.php'
            - '.github/workflows/run-tests.yml'
            - 'phpunit.xml.dist'
            - 'composer.json'
            - 'composer.lock'

jobs:
    test:
        runs-on: ${{ matrix.os }}
        timeout-minutes: 5
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                php: [8.5, 8.4, 8.3, 8.2, 8.1]
                stability: [prefer-lowest, prefer-stable]

        name: PHP ${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: ${{ matrix.php }}
                extensions: gd, fileinfo
                coverage: none

            - name: Install dependencies
              run: |
                  composer update --${{ matrix.stability }} --prefer-dist --no-interaction

            - name: List installed dependencies
              run: composer show -D

            - name: Execute tests
              run: vendor/bin/phpunit tests



